### ISSUE TITLE
临时结果存储

### ISSUE THREAD

**Issue by Ghost2097221** [p1g3/JSINFO-SCAN#11]
可以考虑增加一下中间结果的输出，不然一旦程序中间被无意kill或者服务器出问题，跑了很久的信息结果没有输出。。。。就很难受。

**Comment by p1g3** [comment]
额...如果这样可能会慢一些？已经添加了如果Control C结束进程自动保存，如果被kill 目前还没有解决办法 除非爬到一个存一个 这样效率并不高？
