### ISSUE TITLE
提示: 第58行和56行的缩进不对导致无法解析目标传入的txt文件和显示目标为空的问题

### ISSUE THREAD

**Issue by sv3nbeast** [p1g3/JSINFO-SCAN#15]
elif os.path.isfile(target):
            with open(target, 'r+', encoding='utf-8') as f:
                for domain in f:
                    domain = domain.strip()
                    if not domain.startswith(('http://', 'https://')):
                        domain = 'http://www.' + domain
                    self.root_domains.append(domain)
                    self.queue.put(domain)

这样就好啦~

**Comment by jambestwick** [comment]
二级域名www，一级可没有www，带不带www 还牵扯解析的redirect ，还是得再完善下吧

**Comment by sanyue-github** [comment]
wx好像加不上，url文件中的域名会自动带上www，可以手动停吗，因为数据比较多，之前不小心掉了一下全没了。

**Comment by ZSC0810** [comment]
数据比较多，之前不小心掉了一下全没了 确实是个问题
