### ISSUE TITLE
v3版本ip正则表达式不准确

### ISSUE THREAD

**Issue by mux1ng** [p1g3/JSINFO-SCAN#6]
建议改为(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)\.(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)\.(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)\.(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)
避免匹配到非法IP地址如：3.333.333.3333

**Comment by p1g3** [comment]
已修改，感谢提交建议。

**Comment by p1g3** [comment]
你这个正则不太好用，我还是修改回我原来的那个了，欢迎继续反馈。

**Comment by p1g3** [comment]
完善了正则，感谢提交。
