### ISSUE TITLE
api不能爬了吗

### ISSUE THREAD

**Issue by Underwood12** [p1g3/JSINFO-SCAN#7]
如果api文件不能爬那还咋看关键文件。。。。

**Comment by p1g3** [comment]
前面有几个版本，v2是有api支持的。

**Comment by Underwood12** [comment]
你有微信或者qq吗，这玩意半月回复一次

**Comment by p1g3** [comment]
wx：p1g3___

easy-p <notifications@github.com> 于2020年7月26日周日 下午3:21写道：
